### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by KevinRoig**

### CODE REVIEW

**Review by Bruno-Fernandes-37 — APPROVED** [review]

**Comment by Bruno-Fernandes-37** [comment]
https://tenor.com/bkvfd.gif  ca marche pas moi :(

**Comment by Bruno-Fernandes-37** [comment]
<div class="tenor-gif-embed" data-postid="17240653" data-share-method="host" data-aspect-ratio="2.14765" data-width="100%"><a href="https://tenor.com/view/merge-time-got-game-of-thrones-jon-snow-im-ready-gif-17240653">Merge Time Got GIF</a>from <a href="https://tenor.com/search/merge+time-gifs">Merge Time GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by Bruno-Fernandes-37** [comment]
[https://tenor.com/bkvfd.gif ](https://tenor.com/bkvfd.gif )

**Comment by Bruno-Fernandes-37** [comment]
bon j'abandonne 

ok

**Comment by Bruno-Fernandes-37** [comment]
GG kevin !!

**Review by bastienapp — APPROVED** [review]
fusion ok

**Pull request merged**
